# default rules
course:
  class: sfPropelRouteCollection
  options:
    model:          Course
    module:         course
    prefix_path:    course
    column:         id
    with_wildcard_routes: true
  requirements:  { id: "[\d\w]+" }
  
homepage:
  url:   /
  param: { module: main, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
