propel:
  course:
    _attributes:       { phpName: Course }
    id:                { type: varchar(7), required: true, primaryKey: true }
    dept_id:           { type: varchar(4), required: true, foreignTable: department, foreignReference: id }
    descr:             { type: varchar(50), required: true }
    detail_id:         { type: integer, required: false, foreignTable: course_detail, foreignReference: id }
    is_eng:            { type: boolean, required: true, default: 1 }
    
  course_coment:
    _attributes:       { phpName: CourseComment }
    id:                { type: integer, required: true, primaryKey: true }
    user_id:           { type: integer, required: true, foreignTable: user, foreignReference: id }
    course_id:         { type: varchar(7), required: true, foreignTable: course, foreignReference: id }
    comment:           { type: longvarchar, required: true }
    input_dt:          { type: timestamp, required: true }
    
  course_detail:
    _attributes:       { phpName: CourseDetail }
    id:                { type: integer, required: true, primaryKey: true }
    detail_descr:      { type: longvarchar, required: true }
    first_offered:     { type: date, required: false }
    last_offered:      { type: date, required: false }
    
  course_instructor_assoc:
    _attributes:       { phpName: CourseInstructorAssociation }
    id:                { type: integer, required: true, primaryKey: true }
    instructor_id:     { type: integer, required: true, foreignTable: instructor, foreignReference: id }
    course_id:         { type: varchar(7), required: true, foreignTable: course, foreignReference: id }
    eff_date:          { type: date, required: true }
    discipline_id:     { type: integer, required: true, foreignTable: enum_item, foreignReference: id }
    
  course_rating_data:
    _attributes:       { phpName: CourseRating }
    id:                { type: integer, required: true, primaryKey: true }
    user_id:           { type: integer, required: true, foreignTable: user, foreignReference: id }
    field_id:          { type: integer, required: true, foreignTable: rating_field, foreignReference: id }
    course_id:         { type: varchar(7), required: true, foreignTable: course, foreignReference: id }
    rating:            { type: tinyint, required: true }
    input_dt:          { type: timestamp, required: true }

  department:
    _attributes:       { phpName: Department }
    id:                { type: integer, required: true, primaryKey: true }
    descr:             { type: varchar(50), required: true, index: true }
    
  enum_item:
    _attributes:       { phpName: EnumItem }
    id:                { type: integer, required: true, primaryKey: true }
    parent_id:         { type: integer, required: true, foreignTable: enum_item, foreignReference: id }
    descr:             { type: varchar(50), required: true, index: true }
    
  exam:
    _attributes:       { phpName: Exam }
    id:                { type: integer, required: true, primaryKey: true }
    course_id:         { type: varchar(7), required: true, foreignTable: course, foreignReference: id }
    date:              { type: date, required: true }
    descr:             { type: varchar(50), required: true, index: true }
    file_path:         { type: longvarchar, required: true }
    
  exam_comment:
    _attributes:       { phpName: ExamComment }
    id:                { type: integer, required: true, primaryKey: true }
    user_id:           { type: integer, required: true, foreignTable: user, foreignReference: id }
    comment:           { type: longvarchar, required: true }
    input_dt:          { type: timestamp, required: true }

  instructor:
    _attributes:       { phpName: Instructor }
    id:                { type: integer, required: true, primaryKey: true }
    last_name:         { type: varchar(30), required: true, index: true }
    first_name:        { type: varchar(30), required: true, index: true }
    detail_id:         { type: integer, required: false, foreignTable: instructor_detail, foreignReference: id }
    
  instructor_detail:
    _attributes:       { phpName: InstructorDetail }
    id:                { type: integer, required: true, primaryKey: true }
    descr:             { type: longvarchar, required: true }

  rating_field:
    _attributes:       { phpName: RatingField }
    id:                { type: integer, required: true, primaryKey: true }
    descr:             { type: varchar(50), required: true, index: true }
    type_id:           { type: integer, required: true, foreignTable: enum_item, foreignReference: id }
    
  user:
    _attributes:       { phpName: User }
    id:                { type: integer, required: true, primaryKey: true }
    user_name:         { type: varchar(50), required: true, index: true }
    password:          { type: varchar(50), required: true }
    type_id:           { type: integer, required: true, foreignTable: enum_item, foreignReference: id }
    email:             { type: varchar(50), required: true }
    registered_on:     { type: timestamp, required: true }